# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  csv_service:
    class: AppBundle\Service\ParseCsvService
    arguments: ["@doctrine","@validator","%kernel.root_dir%"]
