# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  csv_service:
    class: AppBundle\Service\ParseCsvService
    arguments: ["@doctrine","@validator","%kernel.root_dir%"]
  wotd_service:
      class: AppBundle\Service\WordOfTheDayService
      arguments: ["@doctrine"]
  mail_service:
      class: AppBundle\Service\MailService
      arguments: ["@mailer","@templating"]
  twig_app_extension:
      class: AppBundle\Twig\AppExtension
      tags:
        - {name:twig.extension}
