<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DayWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayWordRepository extends EntityRepository
{
    public function findWotd()
    {

        $qb = $this->createQueryBuilder("a");

        $query = $qb
            ->orderBy("a.id", 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
