<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository
{
    public function findPopularTerms(){
        $qb=$this->createQueryBuilder("a");

        $query=$qb
            ->where('a.nbVotes>25')
            ->getQuery();
        return $query->getResult();
    }
}
